### ISSUE TITLE
wallet address should be optional while adding beneficiary

### ISSUE THREAD

**Issue by manjik-rumsan** [rahataid/rahat-beneficiary-mgmt#138]
MUST
- [x] Make wallet address optional

NICE TO HAVE
- [x] show warning stating wallet address is optional and will be generated by system if not entered
- [x] generate wallet address from backend on single/ bulk addition

This is done in rahat-ui
<img width="1391" alt="Screenshot 2024-04-20 at 11 55 15 AM" src="https://github.com/rahataid/rahat-beneficiary-mgmt/assets/165631495/d207f44d-07ee-4424-970a-9429ac6d1c43">

**Comment by karun-rumsan** [comment]
@manjik-rumsan 
status: priority done

**Comment by karun-rumsan** [comment]
@manjik-rumsan  
required task done
