### ISSUE TITLE
the beneficiary data is not being uploaded after import in https://ct.dev.rahat.io/

### ISSUE THREAD

**Issue by shristi-rumsan** [rahataid/rahat-beneficiary-mgmt#409]
https://jam.dev/c/b4dc7c15-979e-477d-b1a9-b331b586401d

**Comment by Sanjil-rumsan** [comment]
- [ ] Issue while importing beneficiaries from excel sheet.
Jam Video Link: https://jam.dev/c/087b0ec7-e895-4604-9315-a1445b66f965
