### ISSUE TITLE
Issue While editing Profile Only name and Gender is updated but phone, email and wallet address remains same after edit.

### ISSUE THREAD

**Issue by shristi-rumsan** [rahataid/rahat-beneficiary-mgmt#417]

**Comment by shristi-rumsan** [comment]
https://ct.dev.rahat.io/profile#pagination=%7B%22page%22%3A1%2C%22perPage%22%3A10%7D&filters=%7B%7D&selectedListItems=%7B%7D
https://jam.dev/c/9a8da265-4409-4bf4-b9c0-4ae076ba8df8

**Comment by binod-rumsan** [comment]
They should not be updated by design
